name: check

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "30 13 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      GIT_USER_EMAIL: "shenleidi@gmail.com"
      GIT_USER_NAME: "Christopher SHEN"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ssh-key: "${{ secrets.COMMIT_KEY }}"
      - name: Find packages
        shell: bash
        run: |
          git tag
          ./check-version.sh
      - name: Create tags
        shell: bash
        run: |
          ./create-tags.sh
      - name: Push tags
        run: |
          git config --global user.email $GIT_USER_EMAIL && git config --global user.name $GIT_USER_NAME
          git push --tags
